### ISSUE TITLE
Versioning Issues

### ISSUE THREAD

**Issue by raphaeloliveira** [pepibumur/viper-module-generator#11]
Hey guys, can you please check https://github.com/teambox/viper-module-generator/issues/5?

**Comment by pepibumur** [comment]
@raphaeloliveira I'll update it to 0.2.5 :)

**Comment by raphaeloliveira** [comment]
Thank you @pepibumur but can you please also update the homepage link on https://rubygems.org/gems/vipergen? It points to teambox repository.

**Comment by pepibumur** [comment]
Done @raphaeloliveira
