### ISSUE TITLE
Missing tag 0.2.4?

### ISSUE THREAD

**Issue by raphaeloliveira** [pepibumur/viper-module-generator#12]
Hey guys, I think the repo is missing the tag **0.2.4** since [version.rb](https://github.com/pepibumur/viper-module-generator/blob/master/lib/vipergen/version.rb) show the gem is at this version. Am I right?

**Comment by pepibumur** [comment]
Here you have 0.2.5 @raphaeloliveira https://rubygems.org/gems/vipergen
