### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by frowing** [pepibumur/viper-module-generator#6]
It seems to be happening because it can't find the templates directory. It's an issue for me because the `vipergen` gem got installed in the `.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/`
directory and in order to find the template it is looking at  `.rvm/gems/ruby-2.1.1/gems/vipergen-0.2.4/` but it doesn't exist.

This is the whole Stack Trace:
```from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/filemanager.rb:38:in `copy'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/generator.rb:20:in `generate_viper'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/lib/vipergen/viperthor.rb:12:in `generate'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/fran/.rvm/gems/ruby-2.1.1@global/gems/vipergen-0.2.4/bin/vipergen:8:in `<top (required)>'
	from /Users/fran/.rvm/gems/ruby-2.1.1/bin/vipergen:23:in `load'
	from /Users/fran/.rvm/gems/ruby-2.1.1/bin/vipergen:23:in `<main>'
	from /Users/fran/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fran/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by pepibumur** [comment]
@frowing , created a task to work on it. I'm a bit busy
