### ISSUE TITLE
Not updated for Swift 2

### ISSUE THREAD

**Issue by ronanociosoig** [pepibumur/viper-module-generator#9]
The code needs to be modified to work with Swift version 2.0

**Comment by Nandiin** [comment]
+1

**Comment by ACChe** [comment]
Should update to Swift 3 now ? error in Protocols file display - Class methods are only allowed within classes; use 'static' to declare a static method in present version.

**Comment by pepibumur** [comment]
@ACChe this project is not supported anymore. Feel free to fork it and add support to Swift 3.
